### ISSUE TITLE
HEY

### ISSUE THREAD

**Issue by callumrawlinson** [TwistedAsylumMC/TwistedAsylumMC#1]
@TwistedAsylumMC you just tried to join my server primehosting. but it is currently in maintenance if you want to join i can whitelist you if needed

**Comment by TwistedAsylumMC** [comment]
yes

**Comment by mmm545** [comment]
bruh

**Comment by SOF3** [comment]
heh

**Comment by callumrawlinson** [comment]
@mmm545 do you want to get whitelisted

**Comment by ethaniccc** [comment]
@callumrawlinson stop.

**Comment by callumrawlinson** [comment]
ethan. i have a server that uses your anti cheat you should be happy

**Comment by callumrawlinson** [comment]
@ethaniccc :)

**Comment by ethaniccc** [comment]
Why should I be happy when you're advertising this server on random repositories?

**Comment by callumrawlinson** [comment]
a server with a playerbase of over 5k online at one time is using mockingbird! @ethaniccc
